version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: ${APP_NAME}-app
    volumes:
      - .env:/var/www/.env
      - ./app:/var/www
    ports:
      - 9000:9000
    env_file:
      - .env
    networks:
      frontend:
      database:
          ipv4_address: 172.28.1.1
  # The Web Server
  web:
    image: nginx
    container_name: ${APP_NAME}-web
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/
    ports:
      - 80:80
    networks:
      - frontend

  # The Database
  db:
    image: postgres:9.5-alpine
    container_name: ${APP_NAME}-db
    volumes:
        - "dbdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    networks:
      database:
        ipv4_address: 172.28.1.3

volumes:
  dbdata:

networks:
    frontend:
    database:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
