version: '3'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
      # depends_on:
      #   - database
    # working_dir: /var/www
    links:
      - database
    volumes:
      - ./app:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
      # depends_on: 
      #   - app
    # working_dir: /var/www
    volumes:
      - ./app:/var/www/app
    ports:
      - 8080:80
    links:
      - database
      - app

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"

volumes:
  dbdata: